# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# Importar las clases necesarias
from PyQt5.QtWidgets import QApplication, QMainWindow, QHeaderView
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(792, 600)
        MainWindow.setStyleSheet("background-color: rgb(11, 36, 71);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.bt_Editar_Cliente = QtWidgets.QPushButton(self.centralwidget)
        self.bt_Editar_Cliente.setMinimumSize(QtCore.QSize(0, 28))
        self.bt_Editar_Cliente.setStyleSheet("QPushButton {\n"
"    background-color: rgb(165, 215, 232);\n"
"    color: Black;\n"
"    padding: 8px 16px;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #52c5ff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #52c7ff;\n"
"}")
        self.bt_Editar_Cliente.setObjectName("bt_Editar_Cliente")
        self.gridLayout.addWidget(self.bt_Editar_Cliente, 1, 7, 1, 1)
        self.bt_Buscar = QtWidgets.QPushButton(self.centralwidget)
        self.bt_Buscar.setMinimumSize(QtCore.QSize(0, 28))
        self.bt_Buscar.setMaximumSize(QtCore.QSize(500, 100))
        self.bt_Buscar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(165, 215, 232);\n"
"    color: Black;\n"
"    padding: 8px 16px;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #52c5ff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #52c7ff;\n"
"}")
        self.bt_Buscar.setObjectName("bt_Buscar")
        self.gridLayout.addWidget(self.bt_Buscar, 4, 7, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label.setStyleSheet("font: 14pt \"Ubuntu\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.bt_Guardar_Cliente = QtWidgets.QPushButton(self.centralwidget)
        self.bt_Guardar_Cliente.setMinimumSize(QtCore.QSize(75, 28))
        self.bt_Guardar_Cliente.setMaximumSize(QtCore.QSize(250, 16777215))
        self.bt_Guardar_Cliente.setStyleSheet("QPushButton {\n"
"    background-color: rgb(165, 215, 232);\n"
"    color: black;\n"
"    padding: 8px 16px;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #52c5ff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #52c7ff;\n"
"}")
        self.bt_Guardar_Cliente.setObjectName("bt_Guardar_Cliente")
        self.gridLayout.addWidget(self.bt_Guardar_Cliente, 0, 7, 1, 1)
        self.line_Cliente_Apellido_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_Cliente_Apellido_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.line_Cliente_Apellido_2.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 1px solid gray;\n"
"    padding: 4px;\n"
"    border-radius: 6px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #3daee9;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"")
        self.line_Cliente_Apellido_2.setObjectName("line_Cliente_Apellido_2")
        self.gridLayout.addWidget(self.line_Cliente_Apellido_2, 1, 6, 1, 1)
        self.line_Cliente_Apellido_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_Cliente_Apellido_3.setMaximumSize(QtCore.QSize(300, 16777215))
        self.line_Cliente_Apellido_3.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 1px solid gray;\n"
"    padding: 4px;\n"
"    border-radius: 6px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #3daee9;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"")
        self.line_Cliente_Apellido_3.setObjectName("line_Cliente_Apellido_3")
        self.gridLayout.addWidget(self.line_Cliente_Apellido_3, 2, 6, 1, 1)
        self.bt_Vaciar_Cliente = QtWidgets.QPushButton(self.centralwidget)
        self.bt_Vaciar_Cliente.setMinimumSize(QtCore.QSize(0, 28))
        self.bt_Vaciar_Cliente.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_Vaciar_Cliente.setAutoFillBackground(False)
        self.bt_Vaciar_Cliente.setStyleSheet("QPushButton {\n"
"    background-color: rgb(165, 215, 232);\n"
"    color: Black;\n"
"    padding: 8px 16px;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #52c5ff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #52c7ff;\n"
"}\n"
"")
        self.bt_Vaciar_Cliente.setObjectName("bt_Vaciar_Cliente")
        self.gridLayout.addWidget(self.bt_Vaciar_Cliente, 3, 7, 1, 1)
        self.bt_Eliminar_Cliente = QtWidgets.QPushButton(self.centralwidget)
        self.bt_Eliminar_Cliente.setMinimumSize(QtCore.QSize(0, 28))
        self.bt_Eliminar_Cliente.setStyleSheet("QPushButton {\n"
"    background-color: rgb(165, 215, 232);\n"
"    color: Black;\n"
"    padding: 8px 16px;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #52c5ff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #52c7ff;\n"
"}")
        self.bt_Eliminar_Cliente.setObjectName("bt_Eliminar_Cliente")
        self.gridLayout.addWidget(self.bt_Eliminar_Cliente, 2, 7, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setStyleSheet("font: 14pt \"Ubuntu\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("font: 14pt \"Ubuntu\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setStyleSheet("font: 14pt \"Ubuntu\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 5, 1, 1)
        self.line_Cliente_Nombre = QtWidgets.QLineEdit(self.centralwidget)
        self.line_Cliente_Nombre.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 1px solid gray;\n"
"    padding: 4px;\n"
"    border-radius: 6px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #3daee9;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"")
        self.line_Cliente_Nombre.setObjectName("line_Cliente_Nombre")
        self.gridLayout.addWidget(self.line_Cliente_Nombre, 0, 1, 1, 4)
        self.line_Cliente_Apellido = QtWidgets.QLineEdit(self.centralwidget)
        self.line_Cliente_Apellido.setEnabled(True)
        self.line_Cliente_Apellido.setMaximumSize(QtCore.QSize(300, 16777215))
        self.line_Cliente_Apellido.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 1px solid gray;\n"
"    padding: 4px;\n"
"    border-radius: 6px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #3daee9;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"")
        self.line_Cliente_Apellido.setObjectName("line_Cliente_Apellido")
        self.gridLayout.addWidget(self.line_Cliente_Apellido, 0, 6, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setStyleSheet("font: 14pt \"Ubuntu\";\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setStyleSheet("font: 14pt \"Ubuntu\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setStyleSheet("font: 14pt \"Ubuntu\";\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setStyleSheet("font: 14pt \"Ubuntu\";\n"
"color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.line_Cliente_Buscar = QtWidgets.QLineEdit(self.centralwidget)
        self.line_Cliente_Buscar.setMinimumSize(QtCore.QSize(531, 20))
        self.line_Cliente_Buscar.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 1px solid gray;\n"
"    padding: 4px;\n"
"    border-radius: 6px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #3daee9;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"")
        self.line_Cliente_Buscar.setObjectName("line_Cliente_Buscar")
        self.gridLayout.addWidget(self.line_Cliente_Buscar, 4, 1, 1, 6)
        self.line_Cliente_Direccion = QtWidgets.QLineEdit(self.centralwidget)
        self.line_Cliente_Direccion.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 1px solid gray;\n"
"    padding: 4px;\n"
"    border-radius: 6px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #3daee9;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"")
        self.line_Cliente_Direccion.setObjectName("line_Cliente_Direccion")
        self.gridLayout.addWidget(self.line_Cliente_Direccion, 2, 1, 1, 4)
        self.line_Cliente_Apellido_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_Cliente_Apellido_5.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 1px solid gray;\n"
"    padding: 4px;\n"
"    border-radius: 6px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #3daee9;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"")
        self.line_Cliente_Apellido_5.setObjectName("line_Cliente_Apellido_5")
        self.gridLayout.addWidget(self.line_Cliente_Apellido_5, 1, 1, 1, 4)
        self.line_Cliente_Apellido_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_Cliente_Apellido_4.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 1px solid gray;\n"
"    padding: 4px;\n"
"    border-radius: 6px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #3daee9;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"")
        self.line_Cliente_Apellido_4.setObjectName("line_Cliente_Apellido_4")
        self.gridLayout.addWidget(self.line_Cliente_Apellido_4, 3, 1, 1, 1)
        self.tb_Cliente = QtWidgets.QTableWidget(self.centralwidget)
        self.tb_Cliente.setMinimumSize(QtCore.QSize(0, 50))
        self.tb_Cliente.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.tb_Cliente.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.tb_Cliente.setStyleSheet("QTableView QHeaderView::section {\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    background-color: lightgray;\n"
"    padding: 4px;\n"
"    border: none;\n"
"    border-bottom: 1px solid gray;\n"
"}\n"
"\n"
"QTableView {\n"
"    background-color: white;\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"QTableView QScrollBar:vertical {\n"
"    width: 14px;\n"
"    background-color: lightgray;\n"
"}\n"
"\n"
"QTableView QScrollBar::handle:vertical {\n"
"    background-color: gray;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QTableView QScrollBar::add-line:vertical,\n"
"QTableView QScrollBar::sub-line:vertical {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTableView QScrollBar::add-page:vertical,\n"
"QTableView QScrollBar::sub-page:vertical {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTableView QScrollBar:horizontal {\n"
"    height: 14px;\n"
"    background-color: lightgray;\n"
"}\n"
"\n"
"QTableView QScrollBar::handle:horizontal {\n"
"    background-color: gray;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QTableView QScrollBar::add-line:horizontal,\n"
"QTableView QScrollBar::sub-line:horizontal {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTableView QScrollBar::add-page:horizontal,\n"
"QTableView QScrollBar::sub-page:horizontal {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"")
        self.tb_Cliente.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tb_Cliente.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tb_Cliente.setObjectName("tb_Cliente")
        self.tb_Cliente.setColumnCount(7)
        self.tb_Cliente.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_Cliente.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_Cliente.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_Cliente.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_Cliente.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_Cliente.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_Cliente.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_Cliente.setHorizontalHeaderItem(6, item)
        self.tb_Cliente.horizontalHeader().setVisible(True)
        self.tb_Cliente.horizontalHeader().setCascadingSectionResizes(True)
        self.tb_Cliente.horizontalHeader().setDefaultSectionSize(111)
        self.tb_Cliente.horizontalHeader().setSortIndicatorShown(False)
        self.tb_Cliente.horizontalHeader().setStretchLastSection(True)
        self.tb_Cliente.verticalHeader().setDefaultSectionSize(25)
        self.tb_Cliente.verticalHeader().setMinimumSectionSize(23)
        self.gridLayout.addWidget(self.tb_Cliente, 5, 0, 1, 8)
        self.line_Cliente_Nombre.raise_()
        self.label_3.raise_()
        self.bt_Eliminar_Cliente.raise_()
        self.bt_Guardar_Cliente.raise_()
        self.label.raise_()
        self.bt_Editar_Cliente.raise_()
        self.line_Cliente_Direccion.raise_()
        self.tb_Cliente.raise_()
        self.bt_Vaciar_Cliente.raise_()
        self.line_Cliente_Apellido_2.raise_()
        self.line_Cliente_Apellido_3.raise_()
        self.line_Cliente_Apellido_5.raise_()
        self.label_7.raise_()
        self.line_Cliente_Buscar.raise_()
        self.label_8.raise_()
        self.bt_Buscar.raise_()
        self.label_4.raise_()
        self.label_2.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.line_Cliente_Apellido_4.raise_()
        self.line_Cliente_Apellido.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Principal"))
        self.bt_Editar_Cliente.setText(_translate("MainWindow", "Editar"))
        self.bt_Buscar.setText(_translate("MainWindow", "Buscar"))
        self.label.setText(_translate("MainWindow", "ID:"))
        self.bt_Guardar_Cliente.setText(_translate("MainWindow", "Guardar"))
        self.bt_Vaciar_Cliente.setText(_translate("MainWindow", "Vaciar Campos"))
        self.bt_Eliminar_Cliente.setText(_translate("MainWindow", "Eliminar"))
        self.label_4.setText(_translate("MainWindow", "Cedula:"))
        self.label_2.setText(_translate("MainWindow", "Apellido:"))
        self.label_5.setText(_translate("MainWindow", "Telefono:"))
        self.label_6.setText(_translate("MainWindow", "Correo:"))
        self.label_3.setText(_translate("MainWindow", "Id tienda:"))
        self.label_7.setText(_translate("MainWindow", "Nombre:"))
        self.label_8.setText(_translate("MainWindow", "Buscar:"))
        item = self.tb_Cliente.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tb_Cliente.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.tb_Cliente.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Apellido"))
        item = self.tb_Cliente.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Cedula"))
        item = self.tb_Cliente.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tb_Cliente.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Telefono"))
        item = self.tb_Cliente.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "ID_Tienda"))
# Clase principal de la ventana
class VentanaPrincipal(Ui_MainWindow):
    def __init__(self):
        super().__init__()

        # Código para inicializar la interfaz de usuario en Qt Designer

        # Configurar el modo de redimensionamiento de las columnas de tb_cliente
        self.tb_cliente.horizontalHeader().setSectionResizeMode(Ui_MainWindow.Stretch)

        # Establecer el ancho mínimo y máximo de las columnas de tb_cliente
        self.tb_cliente.horizontalHeader().setMinimumSectionSize(100)
        self.tb_cliente.horizontalHeader().setMaximumSectionSize(300)

        # Otro código necesario para la ventana principal

# Crear la aplicación y mostrar la ventana principal
if __name__ == "__main__":
    import sys
    ventana = VentanaPrincipal()
    ventana.show()
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())