# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'materiales_por_pedido.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mw_materiales(object):
    def setupUi(self, mw_materiales):
        mw_materiales.setObjectName("mw_materiales")
        mw_materiales.resize(1221, 703)
        mw_materiales.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(mw_materiales)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(222, 221, 218);\n"
"    border:none;\n"
"}\n"
"QPushButton {\n"
"    background-color:rgb(255, 255, 255);\n"
"    border:1px solid rgb(100,100,100);\n"
"    color:rgb(50,50,50);\n"
"    padding: 8px 16px;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D2D1;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #52c7ff;\n"
"}\n"
"\n"
"QLabel{\n"
"        font-weight:500;\n"
"}\n"
"\n"
"*{\n"
"        font-family:\"Inter\", sans-serif;\n"
"        \n"
"}\n"
"\n"
"QFrame{\n"
"        background-color: rgb(222, 221, 218);\n"
"        border-radius:10%;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 1px solid gray;\n"
"    padding: 4px;\n"
"    border-radius: 6px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #3daee9;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    background-color: white;\n"
"    border: 1px solid gray;\n"
"    padding: 4px;\n"
"    border-radius: 6px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border-color: #3daee9;\n"
"    outline: none;\n"
"}\n"
"\n"
"QTextEdit::hover {\n"
"    background-color: #f0f0f0;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(6, 19, 0, 12)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(29)
        self.gridLayout.setObjectName("gridLayout")
        self.btnEditar = QtWidgets.QPushButton(self.frame)
        self.btnEditar.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 255);\n"
"    border:1px solid rgb(100,100,100);\n"
"    color:rgb(50,50,50);\n"
"    padding: 8px 16px;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D2D1;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #52c7ff;\n"
"}")
        self.btnEditar.setObjectName("btnEditar")
        self.gridLayout.addWidget(self.btnEditar, 1, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMaximumSize(QtCore.QSize(85, 16777215))
        self.label_2.setStyleSheet("background-color: rgb(222, 221, 218);")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.txtPrecioTotal = QtWidgets.QLabel(self.frame)
        self.txtPrecioTotal.setStyleSheet("QLabel{\n"
"        font-weight:500;\n"
"        background-color:#c7c7c7;\n"
"}\n"
"")
        self.txtPrecioTotal.setText("")
        self.txtPrecioTotal.setObjectName("txtPrecioTotal")
        self.gridLayout.addWidget(self.txtPrecioTotal, 1, 3, 1, 1)
        self.btnEliminar = QtWidgets.QPushButton(self.frame)
        self.btnEliminar.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 255);\n"
"    border:1px solid rgb(100,100,100);\n"
"    color:rgb(50,50,50);\n"
"    padding: 8px 16px;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D2D1;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #52c7ff;\n"
"}")
        self.btnEliminar.setObjectName("btnEliminar")
        self.gridLayout.addWidget(self.btnEliminar, 2, 5, 1, 1)
        self.lblId = QtWidgets.QLabel(self.frame)
        self.lblId.setStyleSheet("color: rgb(222, 221, 218);")
        self.lblId.setText("")
        self.lblId.setObjectName("lblId")
        self.gridLayout.addWidget(self.lblId, 3, 0, 1, 1)
        self.txtPrecioUnidadMedida = QtWidgets.QLineEdit(self.frame)
        self.txtPrecioUnidadMedida.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtPrecioUnidadMedida.setObjectName("txtPrecioUnidadMedida")
        self.gridLayout.addWidget(self.txtPrecioUnidadMedida, 2, 1, 1, 1)
        self.btnGuardar = QtWidgets.QPushButton(self.frame)
        self.btnGuardar.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 255);\n"
"    border:1px solid rgb(100,100,100);\n"
"    color:rgb(50,50,50);\n"
"    padding: 8px 16px;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D2D1;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #52c7ff;\n"
"}")
        self.btnGuardar.setObjectName("btnGuardar")
        self.gridLayout.addWidget(self.btnGuardar, 0, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label.setStyleSheet("QLabel{\n"
"        font-weight:500;\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.txtDescripcion = QtWidgets.QLineEdit(self.frame)
        self.txtDescripcion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtDescripcion.setObjectName("txtDescripcion")
        self.gridLayout.addWidget(self.txtDescripcion, 1, 1, 1, 1)
        self.cbUnidadesMedida = QtWidgets.QComboBox(self.frame)
        self.cbUnidadesMedida.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cbUnidadesMedida.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbUnidadesMedida.setStyleSheet("QComboBox{\n"
"        background-color:rgb(255, 255, 255);\n"
"        border:1px solid rgb(100,100,100);\n"
"        color:rgb(50,50,50);\n"
"        border-radius:4px;\n"
"}\n"
"\n"
"")
        self.cbUnidadesMedida.setEditable(False)
        self.cbUnidadesMedida.setMaxVisibleItems(10)
        self.cbUnidadesMedida.setMaxCount(2147483647)
        self.cbUnidadesMedida.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.cbUnidadesMedida.setObjectName("cbUnidadesMedida")
        self.cbUnidadesMedida.addItem("")
        self.cbUnidadesMedida.addItem("")
        self.cbUnidadesMedida.addItem("")
        self.cbUnidadesMedida.addItem("")
        self.cbUnidadesMedida.addItem("")
        self.cbUnidadesMedida.addItem("")
        self.cbUnidadesMedida.addItem("")
        self.gridLayout.addWidget(self.cbUnidadesMedida, 0, 4, 1, 1)
        self.txtNombreMaterial = QtWidgets.QLineEdit(self.frame)
        self.txtNombreMaterial.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtNombreMaterial.setObjectName("txtNombreMaterial")
        self.gridLayout.addWidget(self.txtNombreMaterial, 0, 1, 1, 1)
        self.txtCantidad = QtWidgets.QLineEdit(self.frame)
        self.txtCantidad.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtCantidad.setObjectName("txtCantidad")
        self.gridLayout.addWidget(self.txtCantidad, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_4.setStyleSheet("background-color: rgb(222, 221, 218);")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.btnRefrescar = QtWidgets.QPushButton(self.frame)
        self.btnRefrescar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btnRefrescar.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 255);\n"
"    border:1px solid rgb(100,100,100);\n"
"    color:rgb(50,50,50);\n"
"    padding: 8px 16px;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D2D1;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #52c7ff;\n"
"}")
        self.btnRefrescar.setObjectName("btnRefrescar")
        self.gridLayout.addWidget(self.btnRefrescar, 4, 5, 1, 1)
        self.btnVaciarCampos = QtWidgets.QPushButton(self.frame)
        self.btnVaciarCampos.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 255);\n"
"    border:1px solid rgb(100,100,100);\n"
"    color:rgb(50,50,50);\n"
"    padding: 8px 16px;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D2D1;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #52c7ff;\n"
"}")
        self.btnVaciarCampos.setObjectName("btnVaciarCampos")
        self.gridLayout.addWidget(self.btnVaciarCampos, 3, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setStyleSheet("background-color: rgb(222, 221, 218);")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_3.setStyleSheet("background-color: rgb(222, 221, 218);")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lblBuscar = QtWidgets.QLabel(self.frame)
        self.lblBuscar.setMaximumSize(QtCore.QSize(55, 16777215))
        self.lblBuscar.setStyleSheet("background-color: rgb(222, 221, 218);")
        self.lblBuscar.setObjectName("lblBuscar")
        self.gridLayout.addWidget(self.lblBuscar, 2, 2, 1, 1)
        self.txtBuscar = QtWidgets.QLineEdit(self.frame)
        self.txtBuscar.setStyleSheet("background-color: rgb(246, 245, 244);")
        self.txtBuscar.setObjectName("txtBuscar")
        self.gridLayout.addWidget(self.txtBuscar, 2, 3, 1, 1)
        self.btnBuscar = QtWidgets.QPushButton(self.frame)
        self.btnBuscar.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 255);\n"
"    border:1px solid rgb(100,100,100);\n"
"    color:rgb(50,50,50);\n"
"    padding: 8px 16px;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D2D1;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #52c7ff;\n"
"}")
        self.btnBuscar.setObjectName("btnBuscar")
        self.gridLayout.addWidget(self.btnBuscar, 2, 4, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tw_materiales = QtWidgets.QTableWidget(self.frame)
        self.tw_materiales.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tw_materiales.setStyleSheet("QTableView QHeaderView::section {\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    background-color: lightgray;\n"
"    padding: 4px;\n"
"    border: none;\n"
"    border-bottom: 1px solid gray;\n"
"}\n"
"\n"
"QTableView {\n"
"    background-color: white;\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"QTableView QScrollBar:vertical {\n"
"    width: 14px;\n"
"    background-color: lightgray;\n"
"}\n"
"\n"
"QTableView QScrollBar::handle:vertical {\n"
"    background-color: gray;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QTableView QScrollBar::add-line:vertical,\n"
"QTableView QScrollBar::sub-line:vertical {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTableView QScrollBar::add-page:vertical,\n"
"QTableView QScrollBar::sub-page:vertical {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTableView QScrollBar:horizontal {\n"
"    height: 14px;\n"
"    background-color: lightgray;\n"
"}\n"
"\n"
"QTableView QScrollBar::handle:horizontal {\n"
"    background-color: gray;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QTableView QScrollBar::add-line:horizontal,\n"
"QTableView QScrollBar::sub-line:horizontal {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTableView QScrollBar::add-page:horizontal,\n"
"QTableView QScrollBar::sub-page:horizontal {\n"
"    background-color: transparent;\n"
"}\n"
"")
        self.tw_materiales.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tw_materiales.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tw_materiales.setObjectName("tw_materiales")
        self.tw_materiales.setColumnCount(8)
        self.tw_materiales.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tw_materiales.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tw_materiales.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tw_materiales.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tw_materiales.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tw_materiales.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_materiales.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tw_materiales.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_materiales.setHorizontalHeaderItem(7, item)
        self.tw_materiales.horizontalHeader().setVisible(True)
        self.tw_materiales.horizontalHeader().setCascadingSectionResizes(False)
        self.tw_materiales.horizontalHeader().setDefaultSectionSize(113)
        self.tw_materiales.horizontalHeader().setSortIndicatorShown(True)
        self.tw_materiales.horizontalHeader().setStretchLastSection(True)
        self.tw_materiales.verticalHeader().setCascadingSectionResizes(False)
        self.tw_materiales.verticalHeader().setDefaultSectionSize(60)
        self.tw_materiales.verticalHeader().setHighlightSections(True)
        self.tw_materiales.verticalHeader().setMinimumSectionSize(21)
        self.tw_materiales.verticalHeader().setSortIndicatorShown(False)
        self.tw_materiales.verticalHeader().setStretchLastSection(False)
        self.gridLayout_5.addWidget(self.tw_materiales, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setStyleSheet("font-family:\"Inter\", sans-serif;\n"
"font-size:30px;\n"
"font-weight:500;")
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        mw_materiales.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mw_materiales)
        self.statusbar.setObjectName("statusbar")
        mw_materiales.setStatusBar(self.statusbar)

        self.retranslateUi(mw_materiales)
        self.cbUnidadesMedida.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mw_materiales)

    def retranslateUi(self, mw_materiales):
        _translate = QtCore.QCoreApplication.translate
        mw_materiales.setWindowTitle(_translate("mw_materiales", "Materiales"))
        self.btnEditar.setText(_translate("mw_materiales", "Editar"))
        self.label_2.setText(_translate("mw_materiales", "Descripcion:"))
        self.btnEliminar.setText(_translate("mw_materiales", "Eliminar"))
        self.btnGuardar.setText(_translate("mw_materiales", "Guardar"))
        self.label.setText(_translate("mw_materiales", "Material:"))
        self.cbUnidadesMedida.setItemText(0, _translate("mw_materiales", "lbs"))
        self.cbUnidadesMedida.setItemText(1, _translate("mw_materiales", "ltrs"))
        self.cbUnidadesMedida.setItemText(2, _translate("mw_materiales", "mts"))
        self.cbUnidadesMedida.setItemText(3, _translate("mw_materiales", "pulg"))
        self.cbUnidadesMedida.setItemText(4, _translate("mw_materiales", "galon"))
        self.cbUnidadesMedida.setItemText(5, _translate("mw_materiales", "unidad"))
        self.cbUnidadesMedida.setItemText(6, _translate("mw_materiales", "simpl"))
        self.label_4.setText(_translate("mw_materiales", "Cantidad:"))
        self.btnRefrescar.setText(_translate("mw_materiales", "Refrescar"))
        self.btnVaciarCampos.setText(_translate("mw_materiales", "Vaciar Campos"))
        self.label_5.setText(_translate("mw_materiales", "Precio total:"))
        self.label_3.setText(_translate("mw_materiales", "Precio*UMedida:"))
        self.lblBuscar.setText(_translate("mw_materiales", "Buscar:"))
        self.btnBuscar.setText(_translate("mw_materiales", "Buscar"))
        item = self.tw_materiales.horizontalHeaderItem(0)
        item.setText(_translate("mw_materiales", "Id"))
        item = self.tw_materiales.horizontalHeaderItem(1)
        item.setText(_translate("mw_materiales", "Material"))
        item = self.tw_materiales.horizontalHeaderItem(2)
        item.setText(_translate("mw_materiales", "Descripcion"))
        item = self.tw_materiales.horizontalHeaderItem(3)
        item.setText(_translate("mw_materiales", "Precio*UnidadMedida"))
        item = self.tw_materiales.horizontalHeaderItem(4)
        item.setText(_translate("mw_materiales", "Cantidad"))
        item = self.tw_materiales.horizontalHeaderItem(5)
        item.setText(_translate("mw_materiales", "unidad_de_medida"))
        item = self.tw_materiales.horizontalHeaderItem(6)
        item.setText(_translate("mw_materiales", "Precio Total"))
        item = self.tw_materiales.horizontalHeaderItem(7)
        item.setText(_translate("mw_materiales", "Pedido"))
        self.label_6.setText(_translate("mw_materiales", "Materiales"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mw_materiales = QtWidgets.QMainWindow()
    ui = Ui_mw_materiales()
    ui.setupUi(mw_materiales)
    mw_materiales.show()
    sys.exit(app.exec_())
