# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pedidos.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Pedidos(object):
    def setupUi(self, Pedidos):
        Pedidos.setObjectName("Pedidos")
        Pedidos.resize(875, 779)
        Pedidos.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Pedidos)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(222, 221, 218);\n"
"    border:none;\n"
"}\n"
"QPushButton {\n"
"    background-color:rgb(255, 255, 255);\n"
"    border:1px solid rgb(100,100,100);\n"
"    color:rgb(50,50,50);\n"
"    padding: 8px 16px;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D2D1;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #52c7ff;\n"
"}\n"
"\n"
"QLabel{\n"
"        font-weight:500;\n"
"}\n"
"\n"
"*{\n"
"        font-family:\"Inter\", sans-serif;\n"
"        \n"
"}\n"
"\n"
"QFrame{\n"
"        background-color: rgb(222, 221, 218);\n"
"        border-radius:10%;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 1px solid gray;\n"
"    padding: 4px;\n"
"    border-radius: 6px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #3daee9;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    background-color: white;\n"
"    border: 1px solid gray;\n"
"    padding: 4px;\n"
"    border-radius: 6px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border-color: #3daee9;\n"
"    outline: none;\n"
"}\n"
"\n"
"QTextEdit::hover {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"\n"
"QLabel{\n"
"        font-weight:500;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tb_Pedidos = QtWidgets.QTableWidget(self.frame)
        self.tb_Pedidos.setStyleSheet("QTableView QHeaderView::section {\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    background-color: lightgray;\n"
"    padding: 4px;\n"
"    border: none;\n"
"    border-bottom: 1px solid gray;\n"
"}\n"
"\n"
"QTableView {\n"
"    background-color: white;\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"QTableView QScrollBar:vertical {\n"
"    width: 14px;\n"
"    background-color: lightgray;\n"
"}\n"
"\n"
"QTableView QScrollBar::handle:vertical {\n"
"    background-color: gray;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QTableView QScrollBar::add-line:vertical,\n"
"QTableView QScrollBar::sub-line:vertical {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTableView QScrollBar::add-page:vertical,\n"
"QTableView QScrollBar::sub-page:vertical {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTableView QScrollBar:horizontal {\n"
"    height: 14px;\n"
"    background-color: lightgray;\n"
"}\n"
"\n"
"QTableView QScrollBar::handle:horizontal {\n"
"    background-color: gray;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QTableView QScrollBar::add-line:horizontal,\n"
"QTableView QScrollBar::sub-line:horizontal {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTableView QScrollBar::add-page:horizontal,\n"
"QTableView QScrollBar::sub-page:horizontal {\n"
"    background-color: transparent;\n"
"}\n"
"")
        self.tb_Pedidos.setObjectName("tb_Pedidos")
        self.tb_Pedidos.setColumnCount(4)
        self.tb_Pedidos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_Pedidos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_Pedidos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_Pedidos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_Pedidos.setHorizontalHeaderItem(3, item)
        self.tb_Pedidos.horizontalHeader().setDefaultSectionSize(151)
        self.tb_Pedidos.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.tb_Pedidos)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.dt_pedido = QtWidgets.QDateEdit(self.frame)
        self.dt_pedido.setStyleSheet("QDateEdit {\n"
"    background-color: white;\n"
"    border: 1px solid gray;\n"
"    padding: 4px;\n"
"    border-radius: 6px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QDateEdit:focus {\n"
"    border-color: #3daee9;\n"
"    outline: none;\n"
"}\n"
"\n"
"QDateEdit::hover {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"\n"
"")
        self.dt_pedido.setObjectName("dt_pedido")
        self.gridLayout_5.addWidget(self.dt_pedido, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setStyleSheet("")
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 3, 0, 1, 1)
        self.cb_cliente = QtWidgets.QComboBox(self.frame)
        self.cb_cliente.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 1px solid gray;\n"
"    padding: 4px;\n"
"    border-radius: 6px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #3daee9;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    background-color: #f0f0f0;\n"
"}")
        self.cb_cliente.setObjectName("cb_cliente")
        self.gridLayout_5.addWidget(self.cb_cliente, 1, 1, 1, 1)
        self.line_Id = QtWidgets.QLineEdit(self.frame)
        self.line_Id.setEnabled(False)
        self.line_Id.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 1px solid gray;\n"
"    padding: 4px;\n"
"    border-radius: 6px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #3daee9;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    background-color: #f0f0f0;\n"
"}")
        self.line_Id.setObjectName("line_Id")
        self.gridLayout_5.addWidget(self.line_Id, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setStyleSheet("")
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 1, 0, 1, 1)
        self.line_Descripcion = QtWidgets.QTextEdit(self.frame)
        self.line_Descripcion.setMaximumSize(QtCore.QSize(2000, 40))
        self.line_Descripcion.setStyleSheet("QTextEdit {\n"
"    background-color: white;\n"
"    border: 1px solid gray;\n"
"    padding: 4px;\n"
"    border-radius: 6px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border-color: #3daee9;\n"
"    outline: none;\n"
"}\n"
"\n"
"QTextEdit::hover {\n"
"    background-color: #f0f0f0;\n"
"}")
        self.line_Descripcion.setObjectName("line_Descripcion")
        self.gridLayout_5.addWidget(self.line_Descripcion, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bt_Guardar = QtWidgets.QPushButton(self.frame)
        self.bt_Guardar.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 255);\n"
"    border:1px solid rgb(100,100,100);\n"
"    color:rgb(50,50,50);\n"
"    padding: 8px 16px;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D2D1;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #52c7ff;\n"
"}\n"
"")
        self.bt_Guardar.setObjectName("bt_Guardar")
        self.verticalLayout.addWidget(self.bt_Guardar)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.bt_Editar = QtWidgets.QPushButton(self.frame)
        self.bt_Editar.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 255);\n"
"    border:1px solid rgb(100,100,100);\n"
"    color:rgb(50,50,50);\n"
"    padding: 8px 16px;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D2D1;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #52c7ff;\n"
"}\n"
"")
        self.bt_Editar.setObjectName("bt_Editar")
        self.verticalLayout.addWidget(self.bt_Editar)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.bt_Eliminar = QtWidgets.QPushButton(self.frame)
        self.bt_Eliminar.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 255);\n"
"    border:1px solid rgb(100,100,100);\n"
"    color:rgb(50,50,50);\n"
"    padding: 8px 16px;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D2D1;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #52c7ff;\n"
"}\n"
"")
        self.bt_Eliminar.setObjectName("bt_Eliminar")
        self.verticalLayout.addWidget(self.bt_Eliminar)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.bt_Vaciar = QtWidgets.QPushButton(self.frame)
        self.bt_Vaciar.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 255);\n"
"    border:1px solid rgb(100,100,100);\n"
"    color:rgb(50,50,50);\n"
"    padding: 8px 16px;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D2D1;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #52c7ff;\n"
"}\n"
"")
        self.bt_Vaciar.setObjectName("bt_Vaciar")
        self.verticalLayout.addWidget(self.bt_Vaciar)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.frame, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("font-family:\"Inter\", sans-serif;\n"
"font-size:30px;\n"
"font-weight:500;")
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        Pedidos.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Pedidos)
        self.statusbar.setObjectName("statusbar")
        Pedidos.setStatusBar(self.statusbar)

        self.retranslateUi(Pedidos)
        QtCore.QMetaObject.connectSlotsByName(Pedidos)

    def retranslateUi(self, Pedidos):
        _translate = QtCore.QCoreApplication.translate
        Pedidos.setWindowTitle(_translate("Pedidos", "Pedidos"))
        item = self.tb_Pedidos.horizontalHeaderItem(0)
        item.setText(_translate("Pedidos", "ID"))
        item = self.tb_Pedidos.horizontalHeaderItem(1)
        item.setText(_translate("Pedidos", "Descripcion"))
        item = self.tb_Pedidos.horizontalHeaderItem(2)
        item.setText(_translate("Pedidos", "Fecha del Pedido"))
        item = self.tb_Pedidos.horizontalHeaderItem(3)
        item.setText(_translate("Pedidos", "ID_Cliente"))
        self.label_8.setText(_translate("Pedidos", "Descripción:"))
        self.label_9.setText(_translate("Pedidos", "Fecha del pedido:"))
        self.label_6.setText(_translate("Pedidos", "ID:"))
        self.label_10.setText(_translate("Pedidos", "Cliente:"))
        self.bt_Guardar.setText(_translate("Pedidos", "Guardar"))
        self.bt_Editar.setText(_translate("Pedidos", "Editar"))
        self.bt_Eliminar.setText(_translate("Pedidos", "Eliminar"))
        self.bt_Vaciar.setText(_translate("Pedidos", "Vaciar Campos"))
        self.label.setText(_translate("Pedidos", "Pedidos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Pedidos = QtWidgets.QMainWindow()
    ui = Ui_Pedidos()
    ui.setupUi(Pedidos)
    Pedidos.show()
    sys.exit(app.exec_())
