# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Proveedores.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Proveedores(object):
    def setupUi(self, Proveedores):
        Proveedores.setObjectName("Proveedores")
        Proveedores.resize(800, 600)
        Proveedores.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Proveedores)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(222, 221, 218);\n"
"    border:none;\n"
"}\n"
"QPushButton {\n"
"    background-color:rgb(255, 255, 255);\n"
"    border:1px solid rgb(100,100,100);\n"
"    color:rgb(50,50,50);\n"
"    padding: 8px 16px;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D2D1;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #52c7ff;\n"
"}\n"
"\n"
"QLabel{\n"
"        font-weight:500;\n"
"}\n"
"\n"
"*{\n"
"        font-family:\"Inter\", sans-serif;\n"
"        \n"
"}\n"
"\n"
"QFrame{\n"
"        background-color: rgb(222, 221, 218);\n"
"        border-radius:10%;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 1px solid gray;\n"
"    padding: 4px;\n"
"    border-radius: 6px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #3daee9;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    background-color: white;\n"
"    border: 1px solid gray;\n"
"    padding: 4px;\n"
"    border-radius: 6px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border-color: #3daee9;\n"
"    outline: none;\n"
"}\n"
"\n"
"QTextEdit::hover {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setStyleSheet("QLabel{\n"
"        font-weight:500;\n"
"}\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.formLayout = QtWidgets.QFormLayout(self.frame_6)
        self.formLayout.setObjectName("formLayout")
        self.label_21 = QtWidgets.QLabel(self.frame_6)
        self.label_21.setStyleSheet("")
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.line_id = QtWidgets.QLineEdit(self.frame_6)
        self.line_id.setEnabled(False)
        self.line_id.setStyleSheet("background-color: rgb(246, 245, 244);")
        self.line_id.setObjectName("line_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_id)
        self.label_20 = QtWidgets.QLabel(self.frame_6)
        self.label_20.setStyleSheet("")
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.line_nombre = QtWidgets.QLineEdit(self.frame_6)
        self.line_nombre.setEnabled(True)
        self.line_nombre.setStyleSheet("background-color: rgb(246, 245, 244);")
        self.line_nombre.setObjectName("line_nombre")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.line_nombre)
        self.label_24 = QtWidgets.QLabel(self.frame_6)
        self.label_24.setStyleSheet("")
        self.label_24.setObjectName("label_24")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.line_ruc = QtWidgets.QLineEdit(self.frame_6)
        self.line_ruc.setEnabled(True)
        self.line_ruc.setStyleSheet("background-color: rgb(246, 245, 244);")
        self.line_ruc.setObjectName("line_ruc")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.line_ruc)
        self.label_25 = QtWidgets.QLabel(self.frame_6)
        self.label_25.setStyleSheet("")
        self.label_25.setObjectName("label_25")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.line_correo = QtWidgets.QLineEdit(self.frame_6)
        self.line_correo.setEnabled(True)
        self.line_correo.setStyleSheet("background-color: rgb(246, 245, 244);")
        self.line_correo.setObjectName("line_correo")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.line_correo)
        self.label_22 = QtWidgets.QLabel(self.frame_6)
        self.label_22.setStyleSheet("")
        self.label_22.setObjectName("label_22")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.line_telefono = QtWidgets.QLineEdit(self.frame_6)
        self.line_telefono.setEnabled(True)
        self.line_telefono.setStyleSheet("background-color: rgb(246, 245, 244);")
        self.line_telefono.setObjectName("line_telefono")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.line_telefono)
        self.label_27 = QtWidgets.QLabel(self.frame_6)
        self.label_27.setStyleSheet("")
        self.label_27.setObjectName("label_27")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.line_buscar_proveedores = QtWidgets.QLineEdit(self.frame_6)
        self.line_buscar_proveedores.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_buscar_proveedores.setObjectName("line_buscar_proveedores")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.line_buscar_proveedores)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(9, QtWidgets.QFormLayout.FieldRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem4)
        self.gridLayout.addWidget(self.frame_6, 0, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_23 = QtWidgets.QLabel(self.frame_7)
        self.label_23.setStyleSheet("")
        self.label_23.setObjectName("label_23")
        self.verticalLayout_3.addWidget(self.label_23)
        self.line_direccion = QtWidgets.QTextEdit(self.frame_7)
        self.line_direccion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_direccion.setObjectName("line_direccion")
        self.verticalLayout_3.addWidget(self.line_direccion)
        self.label_26 = QtWidgets.QLabel(self.frame_7)
        self.label_26.setStyleSheet("")
        self.label_26.setObjectName("label_26")
        self.verticalLayout_3.addWidget(self.label_26)
        self.line_catalogo = QtWidgets.QTextEdit(self.frame_7)
        self.line_catalogo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_catalogo.setObjectName("line_catalogo")
        self.verticalLayout_3.addWidget(self.line_catalogo)
        self.gridLayout.addWidget(self.frame_7, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 1)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 255);\n"
"    border:1px solid rgb(100,100,100);\n"
"    color:rgb(50,50,50);\n"
"    padding: 8px 16px;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D2D1;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #52c7ff;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.bt_Guardar = QtWidgets.QPushButton(self.frame_5)
        self.bt_Guardar.setStyleSheet("")
        self.bt_Guardar.setObjectName("bt_Guardar")
        self.verticalLayout_4.addWidget(self.bt_Guardar)
        self.bt_Editar = QtWidgets.QPushButton(self.frame_5)
        self.bt_Editar.setStyleSheet("")
        self.bt_Editar.setObjectName("bt_Editar")
        self.verticalLayout_4.addWidget(self.bt_Editar)
        self.bt_Eliminar = QtWidgets.QPushButton(self.frame_5)
        self.bt_Eliminar.setStyleSheet("")
        self.bt_Eliminar.setObjectName("bt_Eliminar")
        self.verticalLayout_4.addWidget(self.bt_Eliminar)
        self.bt_Vaciar = QtWidgets.QPushButton(self.frame_5)
        self.bt_Vaciar.setStyleSheet("")
        self.bt_Vaciar.setObjectName("bt_Vaciar")
        self.verticalLayout_4.addWidget(self.bt_Vaciar)
        self.bt_Buscar_Proveedor = QtWidgets.QPushButton(self.frame_5)
        self.bt_Buscar_Proveedor.setStyleSheet("")
        self.bt_Buscar_Proveedor.setObjectName("bt_Buscar_Proveedor")
        self.verticalLayout_4.addWidget(self.bt_Buscar_Proveedor)
        self.horizontalLayout.addWidget(self.frame_5)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tb_Proveedor = QtWidgets.QTableWidget(self.frame_3)
        self.tb_Proveedor.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tb_Proveedor.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tb_Proveedor.setObjectName("tb_Proveedor")
        self.tb_Proveedor.setColumnCount(7)
        self.tb_Proveedor.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_Proveedor.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_Proveedor.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_Proveedor.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_Proveedor.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_Proveedor.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_Proveedor.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_Proveedor.setHorizontalHeaderItem(6, item)
        self.tb_Proveedor.horizontalHeader().setDefaultSectionSize(108)
        self.tb_Proveedor.horizontalHeader().setStretchLastSection(True)
        self.tb_Proveedor.verticalHeader().setVisible(True)
        self.verticalLayout_5.addWidget(self.tb_Proveedor)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        Proveedores.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Proveedores)
        self.statusbar.setObjectName("statusbar")
        Proveedores.setStatusBar(self.statusbar)

        self.retranslateUi(Proveedores)
        QtCore.QMetaObject.connectSlotsByName(Proveedores)

    def retranslateUi(self, Proveedores):
        _translate = QtCore.QCoreApplication.translate
        Proveedores.setWindowTitle(_translate("Proveedores", "Proveedores"))
        self.label_21.setText(_translate("Proveedores", "ID:"))
        self.label_20.setText(_translate("Proveedores", "Nombre:"))
        self.label_24.setText(_translate("Proveedores", "RUC:"))
        self.label_25.setText(_translate("Proveedores", "Correo:"))
        self.label_22.setText(_translate("Proveedores", "Teléfono:"))
        self.label_27.setText(_translate("Proveedores", "Buscar:"))
        self.label_23.setText(_translate("Proveedores", "Dirección:"))
        self.label_26.setText(_translate("Proveedores", "Catálogo:"))
        self.bt_Guardar.setText(_translate("Proveedores", "Guardar"))
        self.bt_Editar.setText(_translate("Proveedores", "Editar"))
        self.bt_Eliminar.setText(_translate("Proveedores", "Eliminar"))
        self.bt_Vaciar.setText(_translate("Proveedores", "Vaciar Campos"))
        self.bt_Buscar_Proveedor.setText(_translate("Proveedores", "Buscar"))
        item = self.tb_Proveedor.horizontalHeaderItem(0)
        item.setText(_translate("Proveedores", "ID"))
        item = self.tb_Proveedor.horizontalHeaderItem(1)
        item.setText(_translate("Proveedores", "Nombre"))
        item = self.tb_Proveedor.horizontalHeaderItem(2)
        item.setText(_translate("Proveedores", "RUC"))
        item = self.tb_Proveedor.horizontalHeaderItem(3)
        item.setText(_translate("Proveedores", "Correo electronico"))
        item = self.tb_Proveedor.horizontalHeaderItem(4)
        item.setText(_translate("Proveedores", "Catálogo"))
        item = self.tb_Proveedor.horizontalHeaderItem(5)
        item.setText(_translate("Proveedores", "Teléfono"))
        item = self.tb_Proveedor.horizontalHeaderItem(6)
        item.setText(_translate("Proveedores", "Dirección"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Proveedores = QtWidgets.QMainWindow()
    ui = Ui_Proveedores()
    ui.setupUi(Proveedores)
    Proveedores.show()
    sys.exit(app.exec_())
