# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Registrar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Recursos import Recursos


class Ui_Registrar(object):
    def setupUi(self, Registrar):
        Registrar.setObjectName("Registrar")
        Registrar.setEnabled(True)
        Registrar.resize(800, 600)
        Registrar.setStyleSheet("background-color: rgb(63, 73, 100);")
        self.centralwidget = QtWidgets.QWidget(Registrar)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 30, 741, 541))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:100px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(580, 10, 81, 81))
        self.label.setStyleSheet("\n"
"border-radius: 40px;\n"
"border-image: url(:/Imagenes/Logo MAPA.png);\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(self.frame)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 100, 651, 391))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.line_nombre = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_nombre.setStyleSheet("border: 3px solid black;\n"
"border-radius: 10px;")
        self.line_nombre.setObjectName("line_nombre")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_nombre)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.line_apellido = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_apellido.setStyleSheet("border: 3px solid black;\n"
"border-radius: 10px;")
        self.line_apellido.setObjectName("line_apellido")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.line_apellido)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.SpanningRole, spacerItem1)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.line_usuario = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_usuario.setStyleSheet("border: 3px solid black;\n"
"border-radius: 10px;")
        self.line_usuario.setObjectName("line_usuario")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.line_usuario)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.SpanningRole, spacerItem2)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.line_clave = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_clave.setStyleSheet("border: 3px solid black;\n"
"border-radius: 10px;")
        self.line_clave.setObjectName("line_clave")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.line_clave)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.SpanningRole, spacerItem3)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_6)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(9, QtWidgets.QFormLayout.FieldRole, spacerItem4)
        self.cb_rol = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cb_rol.setStyleSheet("border: 3px solid black;\n"
"color: rgb(0, 0, 0);")
        self.cb_rol.setObjectName("cb_rol")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.cb_rol)
        self.bt_registrar = QtWidgets.QPushButton(self.formLayoutWidget)
        self.bt_registrar.setStyleSheet("border: 3px solid black;\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0.0170455, stop:0.261364 rgba(246, 143, 137, 255), stop:1 rgba(128, 74, 70, 255));")
        self.bt_registrar.setObjectName("bt_registrar")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.bt_registrar)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(60, 30, 311, 41))
        self.label_8.setStyleSheet("font: 25pt \"Ubuntu\";\n"
"")
        self.label_8.setObjectName("label_8")
        Registrar.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Registrar)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        Registrar.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Registrar)
        self.statusbar.setObjectName("statusbar")
        Registrar.setStatusBar(self.statusbar)

        self.retranslateUi(Registrar)
        QtCore.QMetaObject.connectSlotsByName(Registrar)

    def retranslateUi(self, Registrar):
        _translate = QtCore.QCoreApplication.translate
        Registrar.setWindowTitle(_translate("Registrar", "Registrar"))
        self.label_3.setText(_translate("Registrar", "Nombre:"))
        self.line_nombre.setPlaceholderText(_translate("Registrar", "Ingrese un Nombre:"))
        self.label_2.setText(_translate("Registrar", "Apellido:"))
        self.line_apellido.setPlaceholderText(_translate("Registrar", "Ingrese un Apellido:"))
        self.label_5.setText(_translate("Registrar", "Usuario:"))
        self.line_usuario.setPlaceholderText(_translate("Registrar", "Ingrese un Usuario:"))
        self.label_7.setText(_translate("Registrar", "Clave:"))
        self.line_clave.setPlaceholderText(_translate("Registrar", "Ingrese una Clave:"))
        self.label_6.setText(_translate("Registrar", "Rol:"))
        self.cb_rol.setPlaceholderText(_translate("Registrar", "Elige un rol"))
        self.bt_registrar.setText(_translate("Registrar", "Registrar"))
        self.label_8.setText(_translate("Registrar", "Registro de Usuario"))
        Recursos


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Registrar = QtWidgets.QMainWindow()
    ui = Ui_Registrar()
    ui.setupUi(Registrar)
    Registrar.show()
    sys.exit(app.exec_())
