# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Registrar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Proyecto.Recursos import Recursos


class Ui_Registrar(object):
    def setupUi(self, Registrar):
        Registrar.setObjectName("Registrar")
        Registrar.setEnabled(True)
        Registrar.resize(770, 569)
        Registrar.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Registrar.setAcceptDrops(False)
        Registrar.setWindowOpacity(1.0)
        Registrar.setAutoFillBackground(False)
        Registrar.setStyleSheet("")
        Registrar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(Registrar)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("border-image: url(:/Imagenes/Fondo Registrar.jpg);\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(90, 10, 211, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(30, 70, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.line_nombre = QtWidgets.QLineEdit(self.frame_2)
        self.line_nombre.setGeometry(QtCore.QRect(30, 100, 331, 31))
        self.line_nombre.setStyleSheet("border: 3px solid black;\n"
"border-radius: 5px;")
        self.line_nombre.setObjectName("line_nombre")
        self.line_apellido = QtWidgets.QLineEdit(self.frame_2)
        self.line_apellido.setGeometry(QtCore.QRect(30, 170, 331, 31))
        self.line_apellido.setStyleSheet("border: 3px solid black;\n"
"border-radius: 5px;")
        self.line_apellido.setObjectName("line_apellido")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(30, 140, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(30, 212, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.line_usuario = QtWidgets.QLineEdit(self.frame_2)
        self.line_usuario.setGeometry(QtCore.QRect(30, 240, 331, 31))
        self.line_usuario.setStyleSheet("border: 3px solid black;\n"
"border-radius: 5px;")
        self.line_usuario.setObjectName("line_usuario")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(30, 280, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.line_clave = QtWidgets.QLineEdit(self.frame_2)
        self.line_clave.setGeometry(QtCore.QRect(30, 310, 331, 31))
        self.line_clave.setStyleSheet("border: 3px solid black;\n"
"border-radius: 5px;")
        self.line_clave.setObjectName("line_clave")
        self.cb_rol = QtWidgets.QComboBox(self.frame_2)
        self.cb_rol.setGeometry(QtCore.QRect(30, 380, 331, 31))
        self.cb_rol.setStyleSheet("border: 3px solid black;\n"
"color: rgb(0, 0, 0);")
        self.cb_rol.setObjectName("cb_rol_2")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(30, 350, 41, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.bt_registrar = QtWidgets.QPushButton(self.frame_2)
        self.bt_registrar.setGeometry(QtCore.QRect(60, 450, 271, 41))
        self.bt_registrar.setStyleSheet("border: 3px solid black;\n"
"background-color: rgb(63, 73, 100);\n"
"color: rgb(255, 255, 255);")
        self.bt_registrar.setObjectName("bt_registrar")
        self.bt_volver = QtWidgets.QPushButton(self.frame_2)
        self.bt_volver.setGeometry(QtCore.QRect(120, 510, 151, 31))
        self.bt_volver.setStyleSheet("border: 3px solid black;\n"
"background-color: rgb(63, 73, 100);\n"
"color: rgb(255, 255, 255);")
        self.bt_volver.setObjectName("bt_volver")
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame)
        Registrar.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Registrar)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 770, 21))
        self.menubar.setObjectName("menubar")
        Registrar.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Registrar)
        self.statusbar.setObjectName("statusbar")
        Registrar.setStatusBar(self.statusbar)

        self.retranslateUi(Registrar)
        QtCore.QMetaObject.connectSlotsByName(Registrar)

    def retranslateUi(self, Registrar):
        _translate = QtCore.QCoreApplication.translate
        Registrar.setWindowTitle(_translate("Registrar", "Registrar"))
        self.label_13.setText(_translate("Registrar", "Registro de Usuario"))
        self.label_14.setText(_translate("Registrar", "Nombre:"))
        self.line_nombre.setPlaceholderText(_translate("Registrar", "Ingrese un Nombre:"))
        self.line_apellido.setPlaceholderText(_translate("Registrar", "Ingrese un Apellido:"))
        self.label_11.setText(_translate("Registrar", "Apellido:"))
        self.label_9.setText(_translate("Registrar", "Usuario:"))
        self.line_usuario.setPlaceholderText(_translate("Registrar", "Ingrese un Usuario:"))
        self.label_12.setText(_translate("Registrar", "Clave:"))
        self.line_clave.setPlaceholderText(_translate("Registrar", "Ingrese una Clave:"))
        self.cb_rol.setProperty("placeholderText", _translate("Registrar", "Elige un rol"))
        self.label_10.setText(_translate("Registrar", "Rol:"))
        self.bt_registrar.setText(_translate("Registrar", "Registrar"))
        self.bt_volver.setText(_translate("Registrar", "Volver"))
        Recursos


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Registrar = QtWidgets.QMainWindow()
    ui = Ui_Registrar()
    ui.setupUi(Registrar)
    Registrar.show()
    sys.exit(app.exec_())
