# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tienda.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("font-family:\"Inter\", sans-serif;\n"
"background-color: rgb(222, 221, 218);\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("font-size:15px;\n"
"font-family:\"Inter\", sans-serif;\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.formLayout = QtWidgets.QFormLayout(self.frame_3)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lb_id = QtWidgets.QLabel(self.frame_3)
        self.lb_id.setObjectName("lb_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lb_id)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lb_nombre = QtWidgets.QLabel(self.frame_3)
        self.lb_nombre.setObjectName("lb_nombre")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lb_nombre)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lb_direccion = QtWidgets.QLabel(self.frame_3)
        self.lb_direccion.setObjectName("lb_direccion")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lb_direccion)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lb_telefono = QtWidgets.QLabel(self.frame_3)
        self.lb_telefono.setObjectName("lb_telefono")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lb_telefono)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem3)
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lb_email = QtWidgets.QLabel(self.frame_3)
        self.lb_email.setObjectName("lb_email")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lb_email)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bt_editar = QtWidgets.QPushButton(self.frame_4)
        self.bt_editar.setStyleSheet("QPushButton:hover {\n"
"    background-color: #D6D2D1;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #52c7ff;\n"
"}\n"
"QPushButton {\n"
"    background-color:rgb(255, 255, 255);\n"
"    border:1px solid rgb(100,100,100);\n"
"    color:rgb(50,50,50);\n"
"    padding: 8px 16px;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D2D1;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #52c7ff;\n"
"}")
        self.bt_editar.setObjectName("bt_editar")
        self.verticalLayout_2.addWidget(self.bt_editar)
        self.horizontalLayout.addWidget(self.frame_4)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fr_datos_1 = QtWidgets.QFrame(self.frame_2)
        self.fr_datos_1.setStyleSheet("font-size:15px;\n"
"font-family:\"Inter\", sans-serif;\n"
"")
        self.fr_datos_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_datos_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_datos_1.setObjectName("fr_datos_1")
        self.formLayout_2 = QtWidgets.QFormLayout(self.fr_datos_1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lb_nombre_2 = QtWidgets.QLabel(self.fr_datos_1)
        self.lb_nombre_2.setEnabled(True)
        self.lb_nombre_2.setStyleSheet("")
        self.lb_nombre_2.setObjectName("lb_nombre_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb_nombre_2)
        self.line_nombre = QtWidgets.QLineEdit(self.fr_datos_1)
        self.line_nombre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_nombre.setObjectName("line_nombre")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_nombre)
        self.lb_direccion_2 = QtWidgets.QLabel(self.fr_datos_1)
        self.lb_direccion_2.setObjectName("lb_direccion_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lb_direccion_2)
        self.lb_telefono_2 = QtWidgets.QLabel(self.fr_datos_1)
        self.lb_telefono_2.setObjectName("lb_telefono_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lb_telefono_2)
        self.line_telefono = QtWidgets.QLineEdit(self.fr_datos_1)
        self.line_telefono.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_telefono.setObjectName("line_telefono")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.line_telefono)
        self.lb_email_2 = QtWidgets.QLabel(self.fr_datos_1)
        self.lb_email_2.setObjectName("lb_email_2")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lb_email_2)
        self.line_email = QtWidgets.QLineEdit(self.fr_datos_1)
        self.line_email.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_email.setObjectName("line_email")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.line_email)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem6)
        self.line_direccion = QtWidgets.QTextEdit(self.fr_datos_1)
        self.line_direccion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_direccion.setObjectName("line_direccion")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.line_direccion)
        self.horizontalLayout_2.addWidget(self.fr_datos_1)
        self.fr_datos_2 = QtWidgets.QFrame(self.frame_2)
        self.fr_datos_2.setStyleSheet("QPushButton:hover {\n"
"    background-color: #D6D2D1;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #52c7ff;\n"
"}\n"
"QPushButton {\n"
"    background-color:rgb(255, 255, 255);\n"
"    border:1px solid rgb(100,100,100);\n"
"    color:rgb(50,50,50);\n"
"    padding: 8px 16px;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D2D1;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #52c7ff;\n"
"}")
        self.fr_datos_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_datos_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_datos_2.setObjectName("fr_datos_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.fr_datos_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.bt_guardar = QtWidgets.QPushButton(self.fr_datos_2)
        self.bt_guardar.setObjectName("bt_guardar")
        self.verticalLayout_3.addWidget(self.bt_guardar)
        self.bt_vaciar = QtWidgets.QPushButton(self.fr_datos_2)
        self.bt_vaciar.setObjectName("bt_vaciar")
        self.verticalLayout_3.addWidget(self.bt_vaciar)
        self.horizontalLayout_2.addWidget(self.fr_datos_2)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ID:"))
        self.lb_id.setText(_translate("MainWindow", "{id}"))
        self.label_2.setText(_translate("MainWindow", "Nombre:"))
        self.lb_nombre.setText(_translate("MainWindow", "{nombre}"))
        self.label_3.setText(_translate("MainWindow", "Dirección:"))
        self.lb_direccion.setText(_translate("MainWindow", "{direccion}"))
        self.label_4.setText(_translate("MainWindow", "Teléfono:"))
        self.lb_telefono.setText(_translate("MainWindow", "{telefono}"))
        self.label_5.setText(_translate("MainWindow", "Email:"))
        self.lb_email.setText(_translate("MainWindow", "{emaill}"))
        self.bt_editar.setText(_translate("MainWindow", "Editar"))
        self.lb_nombre_2.setText(_translate("MainWindow", "Nombre:"))
        self.lb_direccion_2.setText(_translate("MainWindow", "Dirección:"))
        self.lb_telefono_2.setText(_translate("MainWindow", "Teléfono:"))
        self.lb_email_2.setText(_translate("MainWindow", "Email:"))
        self.bt_guardar.setText(_translate("MainWindow", "Guardar"))
        self.bt_vaciar.setText(_translate("MainWindow", "Vaciar campos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
